In [1]:
import numpy as np
import time
import sys

In [2]:
a = np.array

np array similar to python list, but np array faster, smaller size

In [3]:
#creating 2 list

SIZE = 1000000
l1 = range(SIZE)
l2 = range(SIZE)

In [4]:
#creating 2 np array

a1 = np.arange(SIZE)
a2 = np.arange(SIZE)

In [5]:
start  = time.time()
result = [(x+y) for x,y in zip(l1,l2)]
print("python list took: ",(time.time()-start)*1000)

start = time.time()
result = a1 + a2
print("numpy took: ",(time.time()-start)*1000)

python list took:  151.66974067687988
numpy took:  30.374526977539062


In [6]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])

#we can acces np array just like list
a1[1]

2

In [7]:
a1+a2

array([5, 7, 9])

In [8]:
a1-a2

array([-3, -3, -3])

In [9]:
a1*a2

array([ 4, 10, 18])

In [10]:
a1/a2

array([0.25, 0.4 , 0.5 ])

In [11]:
#2-D array
a=np.array([[1,2],[3,4],[5,6]])

In [12]:
#ndim give dimension
a.ndim

2

In [13]:
#it will give bit size
a.itemsize

4

In [14]:
a.dtype

dtype('int32')

In [15]:
a2=np.array([[1,2],[3,4],[5,6]], dtype=np.float64)

In [16]:
a2.dtype

dtype('float64')

In [17]:
a2

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [18]:
a.size

6

In [19]:
a.shape

(3, 2)

In [20]:
np.array([[1,2],[3,4],[5,6]], dtype=complex)


array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

In [21]:
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
#ravel fn flatten the array into single row
#a.rvael and reshape will not modify array it give generate new array so if we print a again it will normal as before ravel
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [23]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [24]:
#if we want to start with zero values array of 3 rows and 4 column
np.zeros((3,4))
#np.ones((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [25]:
#just like range in list
# in np we have arange
np.arange(1,5)

array([1, 2, 3, 4])

In [26]:
#now increment is 2 number
np.arange(1,6,2)

array([1, 3, 5])

In [27]:
#generating 10 number between 1 and 5 which are linearly spaced
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [28]:
print(a.min())
print(a.max())
print(a.sum())

1
6
21


In [29]:
#axis 0 is y-axis and axis 1 is x-axis

In [30]:
a.sum(axis=0)

array([ 9, 12])

In [31]:
a.sum(axis=1)

array([ 3,  7, 11])

In [32]:
#max, min are generic function apply on array
#sqrt, std are not generic apply with np.

In [33]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [34]:
np.std(a)

1.707825127659933

In [35]:
a3 = np.array([[1,2],[3,4]])
a4 = np.array([[5,6],[7,8]])

In [36]:
#matrix multiplication
a3.dot(a4)

array([[19, 22],
       [43, 50]])

In [37]:
#list slicing also work on array
a4[-1]

array([7, 8])

In [38]:
a4[:1]

array([[5, 6]])

In [39]:
a5=np.array([[6,7,8],[1,2,3],[9,3,2]])
a5

array([[6, 7, 8],
       [1, 2, 3],
       [9, 3, 2]])

In [40]:
#printing element fro array table, with 0th row and 2 column
#row and column start from 0 in Py
a5[0,2]

8

In [41]:
#searching on row 0 and 1 and giving its 2nd column element from both the rows i.e. 3rd in sequence as we start from 0
a5[0:2,2]

array([8, 3])

In [42]:
#from last row giving 0th and 1st element
a5[-1,0:2]

array([9, 3])

In [43]:
a5[:,1:3]

array([[7, 8],
       [2, 3],
       [3, 2]])

In [44]:
for cell in a5.flat:
  print(cell)

6
7
8
1
2
3
9
3
2


In [45]:
b1=np.arange(6).reshape(3,2)
b2=np.arange(6,12).reshape(3,2)

In [46]:
b1

array([[0, 1],
       [2, 3],
       [4, 5]])

In [47]:
b2

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [48]:
np.vstack((b1,b2))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [49]:
np.hstack((b1,b2))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [50]:
b3=np.arange(30).reshape(2,15)
b3

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [51]:
np.hsplit(b3,3)

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]),
 array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]),
 array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [52]:
np.vsplit(b3,2)

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]

In [53]:
b4=np.arange(12).reshape(3,4)
b4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [54]:
c=b4>4
c

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [55]:
#will return values from b4 where corresponding values from c is True
b4[c]

array([ 5,  6,  7,  8,  9, 10, 11])

In [56]:
#replacing with specific values where c is true
b4[c]=-1
b4

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])

In [57]:
c1=np.arange(12).reshape(3,4)
c1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [58]:
for row in c1:
  for cell in row:
    print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [59]:
#with flatten fn no need for 2 for loops
for cell in c1.flatten():
    print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [60]:
#we are going row by row and in each row by order of column elements will be printed
for x in np.nditer(c1,order='C'):
  print(x)

0
1
2
3
4
5
6
7
8
9
10
11


In [61]:
#now it will go by row 1to 3 with element 1 then again row 1 to 3 2nd element
for x in np.nditer(c1,order='F'):
  print(x)

0
4
8
1
5
9
2
6
10
3
7
11


In [62]:
#printing F order but entire column
for x in np.nditer(c1,order='F',flags=['external_loop']):
  print(x)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [63]:
for x in np.nditer(c1,op_flags=['readwrite']):
  x[...]=x*x
c1

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [64]:
c2 = np.arange(3,15,4).reshape(3,1)
c2

array([[ 3],
       [ 7],
       [11]])

In [65]:
for (x,y) in np.nditer([c1,c2]):
  print(x,y)
#for this to work both the array should be same or one of them should be 1

0 3
1 3
4 3
9 3
16 7
25 7
36 7
49 7
64 11
81 11
100 11
121 11


In [1]:
import numpy as np

data = list(map(int, input().split()))
data = np.array(data, int)
print(data.reshape(3,3))

KeyboardInterrupt: Interrupted by user

In [ ]:
import numpy as np

a1 = np.array([int(n) for n in input().split(' ')])
print(a1.reshape(3, 3))